// <auto-generated />
namespace PublicationAssistantSystem.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Addednewpropertiestomodels : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addednewpropertiestomodels));
        
        string IMigrationMetadata.Id
        {
            get { return "201506132227288_Added new properties to models"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
