// <auto-generated />
namespace PublicationAssistantSystem.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddedDivisionIdparametertoEmployeeDAO : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedDivisionIdparametertoEmployeeDAO));
        
        string IMigrationMetadata.Id
        {
            get { return "201506011744146_Added DivisionId parameter to Employee DAO"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
